/*
AUTOGENERATED - DON'T EDIT
Your edits in this file will be overwritten in the next build!
Modify the docusaurus.config.js file at your site's root instead.
*/
export default {
  "title": "飞冰组件",
  "tagline": "ICE Component Cool",
  "url": "https://your-docusaurus-test-site.com",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "https://img.alicdn.com/imgextra/i2/O1CN01jUf9ZP1aKwVvEc58W_!!6000000003312-73-tps-160-160.ico",
  "staticDirectories": [],
  "plugins": [
    "/Users/maoxiaoke/ali-project/cangjie/node_modules/.pnpm/@ice+pkg-plugin-docusaurus@1.0.0-rc.0_afc660cc97fccb3e1716c22bf89ef61d/node_modules/@ice/pkg-plugin-docusaurus/esnext/plugin.js"
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "remarkPlugins": [
            null
          ],
          "routeBasePath": "/"
        },
        "theme": {
          "customCss": "/Users/maoxiaoke/ali-project/cangjie/node_modules/.pnpm/@ice+pkg-plugin-docusaurus@1.0.0-rc.0_afc660cc97fccb3e1716c22bf89ef61d/node_modules/@ice/pkg-plugin-docusaurus/esnext/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "navbar": {
      "title": "飞冰组件",
      "logo": {
        "src": "https://img.alicdn.com/imgextra/i1/O1CN01lZTSIX1j7xpjIQ3fJ_!!6000000004502-2-tps-160-160.png"
      },
      "hideOnScroll": false,
      "items": []
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": []
    },
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "customFields": {},
  "themes": [],
  "titleDelimiter": "|",
  "noIndex": false
};